version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "11:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
    versioning-strategy: increase-if-necessary
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "11:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
    versioning-strategy: increase-if-necessary
