#!/bin/sh

echo -e "\033[1;32m Installing Dependencies.....\033[0m "
npm install


gulp transpile

cd node_modules/appium-xcuitest-driver && gulp transpile && cd ../..
cd node_modules/appium-ios-simulator && gulp transpile && cd ../..
cd node_modules/node-simctl && gulp transpile && cd ../..

papium="$(pwd)"
printf "alias hackpium='node ${papium}'" >> $HOME/.bashrc
source  $HOME/.bashrc



echo "\033[1;32m Finished....\033[0m "
echo "\033[1;32m How to run appium '$ hackpium -p (custom port)'\033[0m "