source 'https://www.rubygems.org'

gem 'appium_lib',         '~> 9.15'
gem 'rest-client',        '~> 2.0.2'
gem 'rspec',              '~> 3.8.0'
gem 'cucumber',           '~> 3.1.2'
gem 'rspec-expectations', '~> 3.8.1'
gem 'spec',               '~> 5.3.4'
gem 'sauce_whisk',        '~> 0.1.0'
gem 'test-unit',          '~> 3.2.8'
gem 'pry'
