# parameters: # No params yet, but may add later

parameters:
  vmImage: 'macOS-latest'
  bundleNodeJSVersion: '16.17.0'
  nodeJSVersion: '16.x'

jobs:
  - job: bundle_and_upload_appium_zip
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CC: gcc
      CXX: g++
    steps:
    - script: gcc --version
      displayName: Print GCC Version
    - task: NodeTool@0
      inputs:
        versionSpec: ${{ parameters.nodeJSVersion }}
    - script: npm install
      displayName: Install NPM Dependencies
    - script: npm run build
      displayName: npm run build
    - script: npm prune --production
      displayName: Get rid of dev dependencies
    - script: |
        curl -o node-darwin.tar.gz https://nodejs.org/dist/v${{ parameters.bundleNodeJSVersion }}/node-v${{ parameters.bundleNodeJSVersion }}-darwin-x64.tar.gz
        mkdir node-darwin-unpacked
        tar -xzf node-darwin.tar.gz -C node-darwin-unpacked/ --strip-components 1
        rm -f node-darwin.tar.gz
        cp node-darwin-unpacked/bin/node node-darwin
        rm -rf node-darwin-unpacked
      displayName: Download NodeJS to bundle it
    - script: npm run zip
      displayName: Create the bundle zip
    - script: npm install
      displayName: Reinstall dev dependencies
    - task: PublishPipelineArtifact@0
      inputs:
        targetPath: appium.zip
        artifactName: appium
    - script: npm run upload
      env:
        GITHUB_TOKEN: $(GITHUB_TOKEN)
      displayName: Upload to appium/appium-build-store Github Releases
