authors:
  jlipps:
    name: "Jonathan Lipps"
    description: "Appium project lead. Learn more about Jonathan at https://jlipps.com"
    avatar: "https://gravatar.com/avatar/fdaadd825d92709bcf7fe76dffa12c40681c6108c67bcddf19478b2d00e3794b.jpg"
    slug: "jlipps"
    url: "https://jlipps.com"

