name: 🐞 Bug Report
description: Create a new bug report.
title: '🐞 bug: <title>'
labels: [Bug, Needs Triage]
body:

  - type: markdown
    attributes:
      value: ':stop_sign: _Make sure you are reporting an issue. For general questions, please use [http://discuss.appium.io](http://discuss.appium.io)._'

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: 'Please [search :mag: the issues](https://github.com/appium/appium/issues) to check if this bug has already been reported.'
      options:
      - label: I have searched the existing issues
        required: true
  
  - type: input
    attributes:
      label: Appium Version
      description: What Appium server version are you running?
      placeholder: Output of `appium --version`
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Appium Host Type
      description: |
        How is your Appium server being hosted? For options other than "Command Line", please add more details under "Further Information".
      options:
        - Command Line
        - Virtual Machine/Docker
        - Cloud Provider (e.g. BrowserStack/Sauce Labs)
        - Other
    validations:
      required: true

  - type: input
    attributes:
      label: Are you using Appium components not maintained by the Appium team?
      description: Refer to the [Appium Ecosystem](http://appium.io/docs/en/latest/ecosystem/) page for officially-supported components.
      placeholder: Please provide the names of any third-party components.

  - type: checkboxes
    attributes:
      label: Is this issue reproducible using the latest components?
      description: |
        You can retrieve the latest server/driver/plugin version number by running `npm info <package-name> version`. If you are not up to date, please try to reproduce your issue after updating all affected components.
      options:
      - label: I confirm the issue is still reproducible with the latest component versions

  - type: textarea
    attributes:
      label: Current Behavior
      description: Describe the problem you are experiencing. **Please do not paste your logs here.** Screenshots are welcome.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: Describe what you expect to happen instead.
    validations:
      required: true

  - type: input
    attributes:
      label: Appium Log
      description: |
        Please create a [Gist](https://gist.github.com) with your _full_ Appium server log and link it here. Alternatively, you can directly attach your logfile in the "Further Information" field below.

        :warning: _Remember to redact or remove any sensitive information!_
      placeholder: 'https://gist.github.com/...'

  - type: textarea
    attributes:
      label: Environment Details
      description: |
        Please provide additional information about your environment; feel free to remove any items which are not relevant.

        :warning: _Remember to redact or remove any sensitive information!_
      value: |
          - Debug details (`appium --show-debug-info`):
          - Last component version(s) which did _not_ exhibit the problem:
          - Platform and version of device under test:
          - Real device or emulator/simulator:

  - type: textarea
    attributes:
      label: Minimal Reproducible Example
      description: |
        Please provide [the smallest, complete code snippet](https://stackoverflow.com/help/minimal-reproducible-example) that Appium's maintainers can run to reproduce the issue. An easy way to get started is to copy [sample code](https://github.com/appium/appium/tree/master/packages/appium/sample-code) and modify it accordingly. Failing this, any sort of reproduction steps are better than nothing!

        If the result is more than a screenful of text _or_ requires multiple files, please:

        - _Attach_ (do not paste) it to this textarea, _or_
        - Put it in a [Gist](https://gist.github.com) and paste the link, _or_
        - Provide a link to a new or existing public repository exhibiting the issue
    validations:
      required: true

  - type: textarea
    attributes:
      label: Further Information
      description: If needed, please provide additional information about your issue (attachments, links, references, etc.).

  - type: markdown
    attributes:
      value: ':stop_sign: _Make sure you are reporting an issue. For general questions, please use [http://discuss.appium.io](http://discuss.appium.io)._'
