version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/sample-code/javascript-wd"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/sample-code/javascript-webdriverio"
    update_schedule: "live"
