export SAUCE_REST_ROOT=https://saucelabs.com/rest/v1
export APPIUM_HOST=ondemand.saucelabs.com
export APPIUM_PORT=80

export IOS_CONCURRENCY=10
export ANDROID_CONCURRENCY=10
export SELENDROID_CONCURRENCY=5
export GAPPIUM_CONCURRENCY=5
export HTTP_RETRIES=3
export HTTP_RETRY_DELAY=5000
export DEBUG_CONNECTION=1
export MOCHA_INIT_TIMEOUT=600000
export LAUNCH_TIMEOUT='{"global":90000,"afterSimLaunch":30000}'
