jobs:
- job: create_release_branch
  pool:
    vmImage: 'macOS 10.14'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
  - script: |
      git config --global user.name "triager"
      git remote add triager https://${GH_TOKEN}@github.com/appium/appium.git > /dev/null 2>&1
      git remote show triager
    displayName: Set TRIAGER as Git user
  - script: npm install
    displayName: Install the Node dependencies
  - script: node ./ci-jobs/scripts/set-rc-tag.js
    displayName: Update version to rc
  - script: npm shrinkwrap
    displayName: Create the shrinkwrap
  - script: |
      export MINOR_VERSION=$(node ./ci-jobs/scripts/output-minor-version.js)
      echo "Creating branch ${MINOR_VERSION}"
      git checkout -b ${MINOR_VERSION}
      git add .
      git commit -m 'Release branch ${MINOR_VERSION}'
      git push --set-upstream triager HEAD:${MINOR_VERSION}
    displayName: Create the MINOR_VERSION branch
  - script: |
      git tag v${MINOR_VERSION}.0-rc.0
      git push --tags triager
    displayName: Git Tag the release candidate
  - script: npm publish --tag rc
    displayName: Publish the release candidate