# parameters: # No params yet, but may add later
jobs:
  - job: update_appium_io
    pool:
      vmImage: 'macOS 10.14'
    variables:
      CC: gcc
      CXX: g++
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
    - script: |
        brew install hub
        pip install mkdocs==0.16.3
        git clone https://triager:$GITHUB_TOKEN@github.com/appium/appium.io.git --branch=gh-pages
        pushd appium.io
        git remote add triager https://triager:$GITHUB_TOKEN@github.com/appium/appium.io
        git checkout -b docs-$BUILD_SOURCEVERSION
        bundle install
        npm install
        npm run build:docs
        git commit -a -n -m 'Updated docs for latest Appium version'
        git push triager docs-$BUILD_SOURCEVERSION
        hub pull-request -b "appium:gh-pages" -h "appium:docs-$BUILD_SOURCEVERSION" -m "Update documentation for latest version"
      displayName: Make branch with Updated Docs and make PR
      env:
        GITHUB_TOKEN: $(GITHUB_TOKEN)