#!/bin/bash

# install node if we are on on cloudbees cloud node
if [[ $NODE_LABELS =~ .*lxc-fedora.* ]]
then
  curl -sS  https://raw.githubusercontent.com/creationix/nvm/v0.23.3/install.sh | ( bash || true )
  source ~/.nvm/nvm.sh
  nvm install 0.10 &> nvm-install.log
fi

# print node and npm versions
nvm use 0.10

# retrieving gulpfile, maybe it should have it's own repo sometimes.
curl -sS -o gulpfile.js $APPIUM_CI_TOOLS_ROOT/gulpfile.js
curl -sS -o package.json $APPIUM_CI_TOOLS_ROOT/package.json

npm install >> npm-install.log 2>&1

