name: Lint PR Commit Messages
on: [pull_request]

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@7dd9e2a3dc350cf687eb1b2a4fadfee8c8e49675 # v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        uses: bahmutov/npm-install@1a235c31658a322a3b024444759650ee6345c26d # tag=v1
        with:
          useRollingCache: true
          install-command: npm ci --foreground-scripts
      - name: Run commitlint
        run: npm run lint:commit -- --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
