# This job only publishes new releases on GitHub and updates the changelog, without publishing to NPM.
# It can be used if the standard release workflow failed and *only* published to NPM.

name: Appium Server Version (Without NPM Publish)

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

jobs:
  version:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && contains(fromJSON('["mykola-mokhnach", "jlipps", "eglitise", "KazuCocoa"]'), github.actor)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Configure git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Setup Node and install deps (LTS)
        uses: ./.github/actions/setup-build
        with:
          node-version: lts/*
          install-command: npm ci
          run-build: 'true'

      - name: Run Lerna version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx lerna version --exact --yes
