name: Publish docs

on:
  workflow_dispatch:
  push:
    # Runs when any new Appium tag is pushed = there is a new release
    # Does not trigger for tags with a slash, e.g. 1.0/beta
    tags:        
      - appium@*
      - '!appium@*beta*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0 # ensure the docs branch is also fetched
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Setup Node and install deps (LTS)
        uses: ./.github/actions/setup-build
        with:
          node-version: lts/*
          install-command: npm ci
          run-build: 'true'
      - name: Install dependencies (Python)
        run: npm run install-docs-deps
      - name: Publish docs
        run: npm run docs:publish
